[package]
name = "myproject-change-this-name"
version = "0.1.0"
authors = ["Put yaself here etc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64-url = "1.4.8"
jelly = { path = "jelly" }
log = "*"
serde = { version = "1" }

[features]
default = ["jelly/template_watcher", "jelly/static"]
production = ["jelly/production"]
