version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.59.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: cargo --version
      - run: cargo install diesel_cli --no-default-features --features "postgres"
      - run:
          name: Run Unit Tests
          command: "cargo test --lib --features test -- --test-threads=1"
      - run:
          name: Setup test server for integration tests
          command: "DATABASE_URL=$DATABASE_URL_TEST diesel setup && PORT=17002 cargo run --features test"
          background: true
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Start chromedriver
          command: chromedriver --port=4444
          background: true
      - run:
          name: Run Integration Tests
          command: "cargo test --features test --test integration_tests -- --concurrency 1"
