version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.59.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test --features test"
