version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: rustup component add llvm-tools-preview
      - run: cargo install cargo-llvm-cov
      - run: cargo install diesel_cli --no-default-features --features "postgres"
      - run: cargo install coveralls
      # - run:
      #     name: Run Unit Tests
      #     command: "RUSTFLAGS='-C instrument-coverage -lgcov' LLVM_PROFILE_FILE='json5format-%m.profraw' cargo +nightly test_unit"
      - run:
          name: Setup test server for integration tests
          command: "DATABASE_URL=$DATABASE_URL_TEST diesel setup && PORT=17002 cargo run --features test"
          background: true
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Start chromedriver
          command: chromedriver --port=4444
          background: true
      # - run:
      #     name: Run Integration Tests
      #     command: "RUSTFLAGS='-C instrument-coverage' LLVM_PROFILE_FILE='json5format-%m.profraw' cargo +nightly test_integration"

      # Run tests and merge coverage
      - run: cargo llvm-cov clean --workspace
      - run: cargo llvm-cov --no-report --lib --features test -- --test-threads=1
      - run: cargo llvm-cov --no-report --features test --test integration_tests -- --concurrency 1
      - run: cargo llvm-cov --no-run --json --output-path=./cov.json
      - run: coveralls --input cov.json circleci

      # Merging coverage
      # - run: ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/llvm-profdata merge -sparse json5format-*.profraw -o json5format.profdata
      # - run: ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/llvm-cov export --use-color --ignore-filename-regex='/.cargo/registry' --instr-profile=json5format.profdata --object target/debug/deps/mainlib-3896b79477c52536 --object target/debug/deps/integration_tests-a2c4b268602466c6 > coverage.json
      # - run: cargo install coveralls
      # - run: coveralls --input coverage.json circleci
