version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: rustup component add llvm-tools-preview
      - run: cargo install cargo-llvm-cov
      - run: cargo install diesel_cli --no-default-features --features "postgres"
      - run: cargo install coveralls
      - run: cargo install grcov --version 0.8.11
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Start chromedriver
          command: chromedriver --port=4444
          background: true

      # Run tests and merge coverage
      - run: cargo llvm-cov clean --workspace
      - run: RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="movey-%m.profraw" cargo test --lib --features test -- --test-threads=1
      - run: RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="movey-%m.profraw" cargo test --features test --test integration_tests -- --concurrency 1
      - run: grcov . --binary-path ./target/debug/ -t coveralls --keep-only "src/*" --keep-only "tests/*" -s . --token $COVERALLS_REPO_TOKEN > coveralls.json
      - run: coveralls --input coveralls.json circleci
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
