INSERT INTO accounts(name, email, password, is_active, is_admin, has_verified_email, created, updated) VALUES
(
    'user1',
    'test1@email.com',
    'pbkdf2_sha256$320000$SM5bpMPapQvs$E8wXPRdc51UM6It9Fqfb5cojOgN1wMzbvcYnWQa3D3A=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'user2',
    'test2@email.com',
    'pbkdf2_sha256$320000$SM5bpMPapQvs$E8wXPRdc51UM6It9Fqfb5cojOgN1wMzbvcYnWQa3D3A=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'user3',
    'test3@email.com',
    'pbkdf2_sha256$320000$SM5bpMPapQvs$E8wXPRdc51UM6It9Fqfb5cojOgN1wMzbvcYnWQa3D3A=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'user4',
    'test4@email.com',
    'pbkdf2_sha256$320000$SM5bpMPapQvs$E8wXPRdc51UM6It9Fqfb5cojOgN1wMzbvcYnWQa3D3A=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'user5',
    'test5@email.com',
    'pbkdf2_sha256$320000$SM5bpMPapQvs$E8wXPRdc51UM6It9Fqfb5cojOgN1wMzbvcYnWQa3D3A=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
