INSERT INTO accounts(name, email, password, is_active, is_admin, has_verified_email, created, updated, slug) VALUES
(
    'user1',
    'test1@email.com',
    'pbkdf2_sha256$320000$TtPNrS5mLj93$lKzC3OG/GYKBsWxDLhImqIH6Yz/8PHphSEL9NAOTkWU=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'user1'
),
(
    'user2',
    'test2@email.com',
    'pbkdf2_sha256$320000$TtPNrS5mLj93$lKzC3OG/GYKBsWxDLhImqIH6Yz/8PHphSEL9NAOTkWU=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'user2'
),
(
    'user3',
    'test3@email.com',
    'pbkdf2_sha256$320000$TtPNrS5mLj93$lKzC3OG/GYKBsWxDLhImqIH6Yz/8PHphSEL9NAOTkWU=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'user3'
),
(
    'user4',
    'test4@email.com',
    'pbkdf2_sha256$320000$TtPNrS5mLj93$lKzC3OG/GYKBsWxDLhImqIH6Yz/8PHphSEL9NAOTkWU=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'user4'
),
(
    'user5',
    'test5@email.com',
    'pbkdf2_sha256$320000$TtPNrS5mLj93$lKzC3OG/GYKBsWxDLhImqIH6Yz/8PHphSEL9NAOTkWU=',
    TRUE,
    FALSE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'user5'
);
