name: Rust Compilation

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:

  compile:
    name: Compile on linux
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jelly
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: set up test .env file
        run: cp .test-env .env
      - name: Install sqlx
        uses: actions-rs/install@v0.1
        with:
          crate: sqlx-cli
          version: latest
      - name: Migrate database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          cargo install --version=0.5.9 sqlx-cli --no-default-features --features postgres
          sqlx migrate run
      - name: Build | Check
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings" # Disallow warnings
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        with:
          command:  build
          args: --features=jelly/email-postmark,jelly/email-sendgrid,jelly/email-smtp

